### PR TITLE
3.8

### PR DESCRIPTION
**Pull request by TerrePorter**

### CODE REVIEW

**Comment by TerrePorter** [comment]
I really am just having a bad day. Can you resend your pull request for 3.8. I just cant seem to create one.

**Comment by mikerogne** [comment]
@TerrePorter what's the issue? you wanted to keep the PHP 5.6 requirement in composer.json?

**Comment by TerrePorter** [comment]
No I merged your pull for https://github.com/TerrePorter/StringBladeCompiler/pull/46 in to 3.5, and I was suppose to put it in to the new 3.8 branch i created. I had to revert the 3.5 back but now i cant seem to get the pull request back to put it in the 3.8 branch. Its been a crazy day

**Comment by mikerogne** [comment]
@TerrePorter Oh okay, I just created a new one based on your 3.8 branch. One sec... and it keeps the PHP >= 5.6.4 requirement. you can bump it up if you want.

**Pull request closed without merging**
